<a name="top"></a>
<div style="width:1000 px">

<div style="float:right; width:98 px; height:98px;">
<img src="https://cdn.miami.edu/_assets-common/images/system/um-logo-gray-bg.png" alt="Miami Logo" style="height: 98px;">
</div>

<h1>MPO 624: Assignment for Maximum Covariance Analysis (MCA, EOF-PC analysis, factor analysis)</h1>

<div style="clear:both"></div>
</div>

<hr style="height:2px;">

### Links to subsections
1. <a href="#read">Building a Matrix</a>
1. <a href="#trunc">SVD Reconstruction</a>
1. <a href="#trunc">Covariance Matricies</a>
1. <a href="#trunc">Eigen deconstruction and reconstruction</a>

## Building a matrix

In [7]:
import numpy as np

matrix1 = np.random.rand(3,2)
print(matrix1)



[[0.2275326  0.10949693]
 [0.65391627 0.79091519]
 [0.45658169 0.30943208]]


## SVD Reconstruction

In [8]:
u, s, vh = np.linalg.svd(matrix1, full_matrices=False)
print(u.shape, s.shape, vh.shape)

np.allclose(matrix1, np.dot(u * s, vh))
np.allclose(matrix1, np.dot(u, np.dot(np.diag(s), vh)))

s[2:] = 0
new_mat = np.dot(u, np.dot(np.diag(s), vh))
print(new_mat)
print(matrix1)


(3, 2) (2,) (2, 2)
[[0.2275326  0.10949693]
 [0.65391627 0.79091519]
 [0.45658169 0.30943208]]
[[0.2275326  0.10949693]
 [0.65391627 0.79091519]
 [0.45658169 0.30943208]]


## Covariance Matricies

In [11]:
two_b2= np.dot(np.transpose(matrix1), matrix1)

three_b3 = np.dot(matrix1, np.transpose(matrix1))

print(two_b2) 
print(three_b3)


[[0.68784441 0.68338746]
 [0.68338746 0.73328463]]
[[0.06376066 0.23539006 0.13776908]
 [0.23539006 1.05315333 0.54330073]
 [0.13776908 0.54330073 0.30421505]]


## Eigen deconstruction and reconstruction

In [26]:
two_evals, two_evects = np.linalg.eig(two_b2)
#print(two_evals, two_evects)

two_b_recon2 = np.dot(two_evects, np.dot(np.diag(two_evals), np.transpose(two_evects)))
print(two_b_recon2)
print(two_b2)

three_evals, three_evects = np.linalg.eig(three_b3)
#print(two_evals, two_evects)

three_b_recon3 = np.dot(three_evects, np.dot(np.diag(three_evals), np.transpose(three_evects)))
print(three_b_recon3)
print(three_b3)


[[0.68784441 0.68338746]
 [0.68338746 0.73328463]]
[[0.68784441 0.68338746]
 [0.68338746 0.73328463]]
[[0.06376066 0.23539006 0.13776908]
 [0.23539006 1.05315333 0.54330073]
 [0.13776908 0.54330073 0.30421505]]
[[0.06376066 0.23539006 0.13776908]
 [0.23539006 1.05315333 0.54330073]
 [0.13776908 0.54330073 0.30421505]]


### The reconstruction of the data set is unable to be computed after Eigen Decomposition for it is a form of SVD specific to square matricies. Because the original matrix is 3x2, we cannot reconstruct the original dataset (matrix1), however the covariance matrices are able to be reconstructed.